---
- name: Ensure package metadata is up to date (dnf)
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Ensure package metadata is up to date (yum)
  ansible.builtin.yum:
    update_cache: true
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: Install Development Tools group (dnf)
  ansible.builtin.dnf:
    name: "@Development Tools"
    state: present
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Install Development Tools group (yum)
  ansible.builtin.yum:
    name: "@Development Tools"
    state: present
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: Install development packages on RHEL-based systems
  ansible.builtin.package:
    name: "{{ base_packages + redhat_extra_packages }}"
    state: present
  vars:
    redhat_extra_packages:
      - gcc
      - gcc-c++
      - gdb
      - ninja-build
