---
- name: Configure common development tools
  hosts: all
  become: true
  gather_facts: true

  vars:
    supported_os_families:
      - debian
      - redhat
    base_packages:
      - git
      - curl
      - wget
      - cmake
      - make
      - pkg-config
      - python3
      - python3-pip
      - unzip

  tasks:
    - name: Ensure operating system family is supported
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] | lower in supported_os_families
        success_msg: "OS family {{ ansible_facts['os_family'] }} is supported"
        fail_msg: >-
          The common-dev-tools playbook currently supports Debian/Ubuntu and
          RHEL/Rocky based distributions.

    - name: Include OS-specific package installation tasks
      ansible.builtin.include_tasks: "tasks/{{ ansible_facts['os_family'] | lower }}.yml"
